server:
    port:8080
spring:
    datasource:
        url: jdbc:mysql://101.132.41.141:3306/JitB2C?characterEncoding=utf8&useSSL=false
        username: cqf
        password: admin
        driver-class-name: com.mysql.jdbc.Driver

qiniu:
    accessKey: UwDMLe-DcZ6owIanBcwK77fWHJzkI-G025iHzkYc
    secretKey: ySVZoNvAQos9bDivIxjJC3OjckrYq5mnVFdA9zR4
    bucket: image
    path: p2d8s9nsd.bkt.clouddn.com